# Generated by Django 6.0.2 on 2026-03-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("vehicle_count", models.IntegerField(default=0)),
                ("anomaly_detected", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
